//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Sfx
    {
        public const string BundleName = "sfx";
        public const string BEARATTACK = "BearAttack";
        public const string EAT = "Eat";
        public const string JUMP = "Jump";
        public const string SNOWSTEP1 = "SnowStep1";
        public const string SNOWSTEP2 = "SnowStep2";
    }
}
